### ISSUE TITLE
Feedback / questions

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-cst#1]
Overall, this looks great! I've found it very easy to review and make sense of (although I've only looked in detail at `Types.hs` so far).

Is this declaration set up the way it is because comments after a given token are only considered trailing comments if they appear on the same line? What happens if I put some line comments on their own lines at the end of a module?
https://github.com/natefaubion/purescript-cst/blob/8b80d8e1392ae125e72fb1025977967b6fb6c860/src/Language/PureScript/CST/Types.hs#L28-L32

It might be worth mentioning a small naming collision: in an instance declaration, what the GHC user guide calls the "instance head" is the combination of the `instClass` and the `instTypes` fields here. (Also, the GHC user guide calls the `instConstraints` part the _instance context_). See [the GHC user guide's section on instances](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#instance-declarations). I'm not suggesting you change this (especially since "head" already seems to have a consistent meaning within this file), just perhaps worth being aware of.
https://github.com/natefaubion/purescript-cst/blob/8b80d8e1392ae125e72fb1025977967b6fb6c860/src/Language/PureScript/CST/Types.hs#L228-L235

It might make sense to call the condition in an if-then-else `iteCondition`, or perhaps just `iteCond`?
https://github.com/natefaubion/purescript-cst/blob/8b80d8e1392ae125e72fb1025977967b6fb6c860/src/Language/PureScript/CST/Types.hs#L327-L334

Perhaps it would be a bit clearer to say "precedence" rather than just "num"? Also is there a reason you went for `Integer`? I'm pretty sure we only allow single digits there at the moment so I think `Int` ought to suffice (unless you're thinking of lifting that restriction perhaps?)
https://github.com/natefaubion/purescript-cst/blob/8b80d8e1392ae125e72fb1025977967b6fb6c860/src/Language/PureScript/CST/Types.hs#L237-L244

The `Ident` type allows for qualification, but type variables (like the ones here) can't be qualified. Is it worth considering separating the types for things which can and cannot be qualified?
https://github.com/natefaubion/purescript-cst/blob/8b80d8e1392ae125e72fb1025977967b6fb6c860/src/Language/PureScript/CST/Types.hs#L222-L226

**Comment by hdgarrood** [comment]
Also, I think this parser might handle unary negation differently to the existing parser. At the moment, `f -x` becomes `(-) f x`, not `f (negate x)`. If you want to apply a function to a negated value, you have to write `f (-x)`.

**Comment by hdgarrood** [comment]
(If you've found a good way of making unary negation more comfortable to use though, I'm definitely open to discussing that.)

**Comment by natefaubion** [comment]
> Is this declaration set up the way it is because comments after a given token are only considered trailing comments if they appear on the same line? What happens if I put some line comments on their own lines at the end of a module?

Yes, trailing comments are always at the end of the line. Trailing module comments are now part of the `Module` data type.
https://github.com/natefaubion/purescript-cst/blob/8bdcdd853e5da48c695f2716ca87065677e59e57/src/Language/PureScript/CST/Types.hs#L146

> It might be worth mentioning a small naming collision: in an instance declaration, what the GHC user guide calls the "instance head" is the combination of the instClass and the instTypes fields here.

Yes, I'm aware of this. I just wanted a fairly consistent term for things in a declaration before the `where` or body; the thing that is used to dispatch a declaration. I'm open to ideas.

> It might make sense to call the condition in an if-then-else iteCondition, or perhaps just iteCond?

Yeah I think this is probably a better name.

> Perhaps it would be a bit clearer to say "precedence" rather than just "num"? Also is there a reason you went for Integer? I'm pretty sure we only allow single digits there at the moment so I think Int ought to suffice (unless you're thinking of lifting that restriction perhaps?)

I think the `Integer` thing was just an oversight. I believe the current parser allows anything 0 and above.

> The Ident type allows for qualification, but type variables (like the ones here) can't be qualified. Is it worth considering separating the types for things which can and cannot be qualified?

That's fair. At one point I was going to switch it over, but then wanted to just keep moving forward without obsessing over it 😆. 

> Also, I think this parser might handle unary negation differently to the existing parser. At the moment, f -x becomes (-) f x, not f (negate x). If you want to apply a function to a negated value, you have to write f (-x).

I think it parses the way you'd expect now. `f -x` parses as a binary operator (which is what the current compiler does). `f - -x` parses as a binary operator and unary negation. I may have things switched around at some point, but I believe it's correct now.

Thanks for looking over it!

**Comment by hdgarrood** [comment]
> I think the Integer thing was just an oversight. I believe the current parser allows anything 0 and above.

So it does! Thanks for your responses, this all makes sense.

**Comment by natefaubion** [comment]
Oh the reason it's `Integer` is because that's how the parser handles integer literals.
