### ISSUE TITLE
Imported-as names may contain periods

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-cst#2]
For example, the current parser allows this but cst doesn't:

```
import Foo as Bar.Baz
```

**Comment by natefaubion** [comment]
This is because of `proper` instead of `properIdent`:
https://github.com/natefaubion/purescript-cst/blob/55cc6b29df163491042a93fb75e24dd3313a9779/src/Language/PureScript/CST/Parser.y#L422
