### ISSUE TITLE
Departure from current parser with applicative do

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-cst#9]
The following is parseable with the current parser but not cst.
```purescript
module Test where
test = ado
  in
    foo
```
cst gives:
> Unexpected or mismatched indentation at line 4, column 3
> Unexpected end of input at line 6, column 1

**Comment by natefaubion** [comment]
Should this be disallowed in the current parser?

**Comment by hdgarrood** [comment]
As in, an applicative do expression with no elements?

**Comment by natefaubion** [comment]
If this were allowed, then it should also allow an empty `let in foo`, which would allow empty binding contexts in general. I'm not sure why we would want to support this other than the ability to comment stuff out without deleting the let/in.

**Comment by natefaubion** [comment]
> As in, an applicative do statement with no elements?

Yes. Why do we support applicative-do with no elements?

**Comment by hdgarrood** [comment]
I'm not sure we considered not doing so. See https://github.com/purescript/purescript/pull/2889

**Comment by hdgarrood** [comment]
Here's another file which the current parser succeeds on but cst fails. This one doesn't have an empty `ado` either:
```purescript
module Test where
main =
  { foo: 0
  , bar: \x -> ado
     y <- thing x
     let z = y
     in {z}
  }
```
CST says:
> Unexpected token "}" at line 8, column 3

**Comment by hdgarrood** [comment]
I don't see what the connection to `let in foo` is, though; it's not clear to me that allowing empty applicative-do but not allowing `let in foo` is inconsistent.

**Comment by natefaubion** [comment]
I think your latter example is because it's parsing `let/in` as an expression, and it's expecting another `in`.

**Comment by natefaubion** [comment]
I've fixed both of the `ado` cases. I did not change the grammar to account for `let/in`, but `let/in` is effectively disallowed in `ado` via the layout algorithm.
